server:
  port: 8123
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件上传的最大大小
      max-request-size: 40MB # 请求中所有文件的总大小
  application:
    name: picture_cloud_backend
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 112358
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 1
  # session失效时间
  session:
    timeout: 86400
    store-type: redis
mybatis-plus:
  configuration:
    # 下划线转驼峰:关闭
    map-underscore-to-camel-case: false
    # 控制台打印sql语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1           # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0       # 逻辑未删除值(默认为 0)
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: K接口文档
    version: 1.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ninja.picture_cloud_backend.controller
## 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: xxx
#    secretId: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

